#!/usr/bin/env python3
"""Autoresearch loop runner for Dubweave — loop3

Edits `normalizer_rules.json` in-place using small, one-hypothesis edits.
After each run, follows KEEP/DISCARD policy: commit on KEEP, git checkout on DISCARD.
"""
import json
import subprocess
import sys
import os
from pathlib import Path
import time

ROOT = Path(__file__).resolve().parent
RULES = ROOT / "normalizer_rules.json"
BENCH = [sys.executable, str(ROOT / "benchmark_loop3.py")]
RESULTS = ROOT / "results_loop3.tsv"

MAX_EXPERIMENTS = 60
MAX_DISCARD_STREAK = 5


def read_best_S():
    if not RESULTS.exists():
        return None
    best = None
    import csv
    with open(RESULTS, newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f, delimiter='\t'):
            if row.get('status') in ('KEEP', 'BASELINE'):
                try:
                    s = float(row['S'])
                    if best is None or s > best:
                        best = s
                except Exception:
                    pass
    return best


def git(cmd):
    return subprocess.run(['git'] + cmd, cwd=ROOT, check=False, capture_output=True, text=True)


def run_bench(desc, baseline=False, verbose=False):
    cmd = BENCH + (['--baseline'] if baseline else []) + (['--verbose'] if verbose else []) + ['-d', desc]
    print('Running:', ' '.join(cmd))
    return subprocess.run(cmd, cwd=ROOT).returncode


def load_rules():
    return json.loads(RULES.read_text(encoding='utf-8'))


def save_rules(cfg):
    RULES.write_text(json.dumps(cfg, indent=2, ensure_ascii=False) + "\n", encoding='utf-8')


def add_rule(cfg, pattern, replacement, note):
    rules = cfg.get('rules', [])
    # avoid duplicate by pattern
    for r in rules:
        if r.get('pattern') == pattern and r.get('replacement') == replacement:
            return False
    rules.append({"pattern": pattern, "replacement": replacement, "note": note})
    cfg['rules'] = rules
    return True


def remove_rule_by_pattern(cfg, pattern):
    rules = cfg.get('rules', [])
    new = [r for r in rules if r.get('pattern') != pattern]
    changed = len(new) != len(rules)
    cfg['rules'] = new
    return changed


def add_gerund_verbs(cfg, verbs):
    rules = cfg.get('rules', [])
    for r in rules:
        if r.get('type') == 'gerund':
            existing = set(r.get('verbs', []))
            added = False
            for v in verbs:
                if v not in existing:
                    existing.add(v)
                    added = True
            if added:
                r['verbs'] = sorted(existing)
                return True
            return False
    # not found — append a gerund rule
    rules.append({"type": "gerund", "note": "autogenerated", "verbs": sorted(set(verbs))})
    cfg['rules'] = rules
    return True


def refine_pattern_context(cfg, pattern, new_pattern):
    rules = cfg.get('rules', [])
    for r in rules:
        if r.get('pattern') == pattern:
            r['pattern'] = new_pattern
            return True
    return False


MUTATIONS = [
    ("add_apanhar_pegar", lambda cfg: add_rule(cfg, "\\bapanhar\\b", "pegar", "vocab")),
    ("add_conduzir_dirigir", lambda cfg: add_rule(cfg, "\\bconduzir\\b", "dirigir", "vocab")),
    ("add_frigorifico_geladeira", lambda cfg: add_rule(cfg, "\\bfrigor[ií]fico\\b", "geladeira", "vocab")),
    ("add_pequeno-almoco", lambda cfg: add_rule(cfg, "\\bpequeno-?almo[cç]o\\b", "café da manhã", "vocab")),
    ("add_talho_acougue", lambda cfg: add_rule(cfg, "\\btalho\\b", "açougue", "vocab")),
    ("add_trazes_traz", lambda cfg: add_rule(cfg, "\\btrazes\\b", "traz", "verb_2p")),
    ("add_ouves_ouve", lambda cfg: add_rule(cfg, "\\bouves\\b", "ouve", "verb_2p")),
    ("add_vivias_vivia", lambda cfg: add_rule(cfg, "\\bvivias\\b", "vivia", "verb_2p")),
    ("add_tinhas_tinha", lambda cfg: add_rule(cfg, "\\btinhas\\b", "tinha", "verb_2p")),
    ("add_gerund_verbs_batch", lambda cfg: add_gerund_verbs(cfg, [
        "fumar","comer","beber","escrever","ler","subir","sair","abrir",
        "conduzir","sorrir","construir","produzir","introduzir"
    ])),
    ("refine_passeio_context", lambda cfg: refine_pattern_context(cfg, "\\bpasseio\\b", "(?<!dar\\s)\\bpasseio\\b")),
    ("remove_apenas", lambda cfg: remove_rule_by_pattern(cfg, "\\bapenas\\b")),
]


def main():
    # ensure in git repo
    try:
        git(['rev-parse', '--is-inside-work-tree'])
    except Exception:
        print('ERROR: not a git repository', file=sys.stderr)
        sys.exit(1)

    # baseline if none
    best = read_best_S()
    if best is None:
        print('No baseline found — recording current rules as BASELINE')
        run_bench('original baseline', baseline=True)
        best = read_best_S()
        print('Baseline S =', best)

    experiments = 0
    discard_streak = 0
    mut_index = 0

    while experiments < MAX_EXPERIMENTS and discard_streak < MAX_DISCARD_STREAK:
        experiments += 1
        name, func = MUTATIONS[mut_index % len(MUTATIONS)]
        mut_index += 1

        cfg = load_rules()
        changed = func(cfg)
        if not changed:
            print(f"Mutation {name} made no change — skipping")
            continue

        save_rules(cfg)
        desc = f"exp#{experiments} {name}"
        run_bench(desc)
        time.sleep(0.2)

        # read last line of results
        import csv
        last = None
        if Path(RESULTS).exists():
            with open(RESULTS, newline='', encoding='utf-8') as f:
                rows = list(csv.DictReader(f, delimiter='\t'))
                if rows:
                    last = rows[-1]

        if not last:
            print('No result logged; aborting')
            break

        status = last.get('status', '')
        S = last.get('S')
        print(f"Experiment {experiments}: status={status} S={S} desc={last.get('description')}")

        if status == 'KEEP' or status == 'BASELINE':
            git(['add', str(RULES)])
            git(['commit', '-m', f'KEEP: {desc}'])
            discard_streak = 0
            best = read_best_S()
        else:
            print('DISCARD — restoring previous rules')
            git(['checkout', '--', str(RULES)])
            discard_streak += 1

    print('\nRun finished.')
    print('Best S =', read_best_S())


if __name__ == '__main__':
    main()
